name: Veracode Scan

on:
  push:
    branches:
      - main
      - release/*
    tags:
      - "*"
  pull_request:
     types:
      - opened
      - reopened
      - synchronize
      - closed
  workflow_dispatch:

jobs:
  veracode-sast-task:
    runs-on: ubuntu-latest
    name: Veracode SAST policy scan

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: create new package-lock.json
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > .npmrc
          npm install
      - name: ZIP source folder
        run: zip -r app.zip src package-lock.json
      - name: Run Veracode Policy scan
        uses: veracode/veracode-uploadandscan-action@0.2.10
        with:
          appname: "tsp-toolkit"
          createprofile: false
          version: ${{ case( (endsWith(github.ref, 'main') && contains(github.head_ref, 'release/') && github.event.pull_request.merged ), 'release', (startsWith(github.ref, 'refs/release/') && startsWith(github.head_ref, 'refs/pull/')), 'pr-${{ github.ref_name}}', 'other') }}-${{ github.sha }}-${{github.job}}-${{github.run_id}}-${{github.run_attempt}}
          filepath: "app.zip"
          scantimeout: 30
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
